### ISSUE TITLE
[Bug]: Auto-layout when making a sibling card causes child cards to overlap

### ISSUE THREAD

**Issue by duckfarts** [Quorafind/Obsidian-Canvas-MindMap#26]
### Bug Description

Currently, when you hit Enter to create a sibling node, it updates the layout to put all of that level's nodes together. This is problematic when you have a bunch of child nodes already, and causes your new child nodes to overlap with other ones.

I can see auto-layout being very helpful, but it would need to happen at multiple levels (which might be difficult if multiple cards connect to the same card).

Alternatively, it would be helpful to have an option to Disable Auto-layout so that creating a sibling card just makes another card under the current one, but doesn't update the layout.

### Relevant Screenshot

![Auto-layout issue](https://user-images.githubusercontent.com/24978179/218635653-fed212b2-144a-4d0d-8240-db08b44b9842.png)

### To Reproduce

1. Make a few cards at the same level
2. Add child cards to those cards
3. Select a card created in step 1 and create a new sibling card
4. Create child cards for the new card from step 3

### Obsidian Version

v1.1.9

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by devinat1** [comment]
Can confirm same issue occurs with mine as well on 1.1.9

**Comment by wrightwriter** [comment]
not the easiest to solve, also debatable if desirable.

**Comment by KuiyueRO** [comment]
this [fork](https://github.com/xiehengjian/Obsidian-Canvas-MindMap) fix this.

**Comment by a823002162** [comment]
> this [fork](https://github.com/xiehengjian/Obsidian-Canvas-MindMap) fix this.↳

it really work,dude thank you 
![GIF 5-25-2023 5-23-05 PM](https://github.com/Quorafind/Obsidian-Canvas-MindMap/assets/39456045/887be49f-b637-49ce-b6a4-d254650d78f4)

**Comment by Quorafind** [comment]
@tcardlab  It's quite interesting, thank you for explaining all this to me. To be honest, I am shocked that someone thinks my code quality is so good. However, I don't agree with the behavior of using my code, which is under the GPL v3 license, for proprietary purposes just for profit.

The reason I chose this license instead of MIT in the first place was because the functionality related to MindMap can easily be resold, and I also hope that the relevant operational code can benefit subsequent developers.

If, as you say, he has gone proprietary without even altering some basic code logic, I think this behavior is inappropriate. If he plans to list it in the Obsidian plugin market in the future, I might raise an objection.

However, if he just created a similar plugin based on the same internal interfaces of Obsidian, I might not do much. But I think he needs to realize that although this issue is minor, similar actions in larger commercial endeavors in the future could have a much bigger impact.

**Comment by Quorafind** [comment]
Supported.
